jobs:
  # All tasks on Linux
  - job: build_all_linux
    displayName: Build all tasks (Linux)
    timeoutInMinutes: 120
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 6.0.x
      - script: cd scripts && bash elasticsearch-linux.sh
        displayName: 'Start an elasticsearch'
      - script: bash build.sh --target=Test-with-Codecov
        displayName: 'Build and Test'
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
      - task: reportgenerator@5
        displayName: ReportGenerator
        inputs:
          reports: '$(Build.SourcesDirectory)/test/*/TestResults/*/coverage.cobertura.xml'
          targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
          reporttypes: 'Cobertura'
          assemblyfilters: '-xunit*'
      - script: bash build.sh --target=Upload-Coverage-Azure
        displayName: 'Upload data to Codecov'